runtime: python38
instance_class: F4


error_handlers:
  - error_code: over_quota
    file: templates/error500.html

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
  - url: /
    script: auto
    secure: always
    redirect_http_response_code: 301
  - url: /(.*)$
    script: auto
    secure: always
    redirect_http_response_code: 301
