runtime: python38
instance_class: F2

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
  - url: /
    script: auto
    secure: always
    redirect_http_response_code: 301
  - url: /(.*)$
    script: auto
    secure: always
    redirect_http_response_code: 301
